# Generated by Django 3.2.9 on 2022-02-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=5000)),
                ('last_name', models.CharField(max_length=5000)),
                ('date', models.CharField(max_length=5000)),
                ('time', models.CharField(max_length=5000)),
                ('message', models.CharField(max_length=5000)),
            ],
        ),
    ]
